# -*- coding: utf-8 -*-
"""
点击生成按钮，弹窗的第二步页面，负责配置生成器的输出配置
"""
from PyQt5 import QtWidgets, QtCore

_author_ = 'luwt'
_date_ = '2020/7/18 11:47'


def setup_tab_ui(confirm_select_ui):
    """
    构建选择生成器的tab标签界面
    :param confirm_select_ui: 弹窗确认生成器配置页的主窗口对象
    """
    confirm_select_ui.widget_generator = QtWidgets.QWidget(confirm_select_ui.dialog)
    confirm_select_ui.widget_generator.setObjectName("widget")
    confirm_select_ui.verticalLayout_2 = QtWidgets.QVBoxLayout(confirm_select_ui.widget_generator)
    confirm_select_ui.verticalLayout_2.setObjectName("verticalLayout_2")
    confirm_select_ui.tabWidget = QtWidgets.QTabWidget(confirm_select_ui.widget_generator)
    confirm_select_ui.tabWidget.setObjectName("tabWidget")
    # mybatis标签页
    setup_mybatis_tab_ui(confirm_select_ui)
    # spring标签页
    setup_spring_tab_ui(confirm_select_ui)

    confirm_select_ui.tabWidget.addTab(confirm_select_ui.spring_tab, "")
    confirm_select_ui.verticalLayout_2.addWidget(confirm_select_ui.tabWidget)
    # 按钮部分
    confirm_select_ui.splitter = QtWidgets.QSplitter(confirm_select_ui.widget_generator)
    confirm_select_ui.splitter.setOrientation(QtCore.Qt.Horizontal)
    confirm_select_ui.splitter.setObjectName("splitter")
    confirm_select_ui.buttonBox = QtWidgets.QDialogButtonBox(confirm_select_ui.splitter)
    confirm_select_ui.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel | QtWidgets.QDialogButtonBox.Ok)
    confirm_select_ui.buttonBox.setObjectName("buttonBox")
    confirm_select_ui.buttonBox.setLayoutDirection(QtCore.Qt.RightToLeft)
    confirm_select_ui.buttonBox_2 = QtWidgets.QDialogButtonBox(confirm_select_ui.splitter)
    confirm_select_ui.buttonBox_2.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel | QtWidgets.QDialogButtonBox.Ok)
    confirm_select_ui.buttonBox_2.setObjectName("buttonBox_2")
    confirm_select_ui.verticalLayout_2.addWidget(confirm_select_ui.splitter)
    confirm_select_ui.verticalLayout.addWidget(confirm_select_ui.widget_generator)

    confirm_select_ui.buttonBox.rejected.connect(confirm_select_ui.pre_step)
    confirm_select_ui.buttonBox_2.rejected.connect(confirm_select_ui.close)

    # 填充文字
    fill_text(confirm_select_ui)


def setup_mybatis_tab_ui(confirm_select_ui):
    """
    构建mybatis生成器配置标签页
    :param confirm_select_ui: 弹窗确认生成器配置页的主窗口对象
    :return:
    """
    confirm_select_ui.mybatis_tab = QtWidgets.QWidget()
    confirm_select_ui.mybatis_tab.setObjectName("mybatis_tab")
    confirm_select_ui.verticalLayout_3 = QtWidgets.QVBoxLayout(confirm_select_ui.mybatis_tab)
    confirm_select_ui.verticalLayout_3.setObjectName("verticalLayout_3")
    confirm_select_ui.mybatis_title = QtWidgets.QLabel(confirm_select_ui.mybatis_tab)
    confirm_select_ui.mybatis_title.setObjectName("mybatis_title")
    confirm_select_ui.verticalLayout_3.addWidget(confirm_select_ui.mybatis_title)
    confirm_select_ui.mybatis_first_blank = QtWidgets.QLabel(confirm_select_ui.mybatis_tab)
    confirm_select_ui.mybatis_first_blank.setText("")
    confirm_select_ui.mybatis_first_blank.setObjectName("mybatis_first_blank")
    confirm_select_ui.verticalLayout_3.addWidget(confirm_select_ui.mybatis_first_blank)
    confirm_select_ui.mybatis_desc = QtWidgets.QLabel(confirm_select_ui.mybatis_tab)
    confirm_select_ui.mybatis_desc.setObjectName("mybatis_desc")
    confirm_select_ui.verticalLayout_3.addWidget(confirm_select_ui.mybatis_desc)
    confirm_select_ui.mybatis_second_blank = QtWidgets.QLabel(confirm_select_ui.mybatis_tab)
    confirm_select_ui.mybatis_second_blank.setText("")
    confirm_select_ui.mybatis_second_blank.setObjectName("mybatis_second_blank")
    confirm_select_ui.verticalLayout_3.addWidget(confirm_select_ui.mybatis_second_blank)
    confirm_select_ui.splitter_lombok = QtWidgets.QSplitter(confirm_select_ui.mybatis_tab)
    confirm_select_ui.splitter_lombok.setOrientation(QtCore.Qt.Horizontal)
    confirm_select_ui.splitter_lombok.setObjectName("splitter_lombok")
    confirm_select_ui.lombok = QtWidgets.QLabel(confirm_select_ui.splitter_lombok)
    confirm_select_ui.lombok.setObjectName("lombok")
    confirm_select_ui.lombok_comboBox = QtWidgets.QComboBox(confirm_select_ui.splitter_lombok)
    confirm_select_ui.lombok_comboBox.setObjectName("lombok_comboBox")
    confirm_select_ui.lombok_comboBox.addItem("")
    confirm_select_ui.lombok_comboBox.addItem("")
    confirm_select_ui.verticalLayout_3.addWidget(confirm_select_ui.splitter_lombok)
    confirm_select_ui.lombok_desc = QtWidgets.QLabel(confirm_select_ui.mybatis_tab)
    confirm_select_ui.lombok_desc.setObjectName("lombok_desc")
    confirm_select_ui.verticalLayout_3.addWidget(confirm_select_ui.lombok_desc)
    confirm_select_ui.splitter_java = QtWidgets.QSplitter(confirm_select_ui.mybatis_tab)
    confirm_select_ui.splitter_java.setOrientation(QtCore.Qt.Horizontal)
    confirm_select_ui.splitter_java.setObjectName("splitter_java")
    confirm_select_ui.java = QtWidgets.QLabel(confirm_select_ui.splitter_java)
    confirm_select_ui.java.setObjectName("java")
    confirm_select_ui.java_lineEdit = QtWidgets.QLineEdit(confirm_select_ui.splitter_java)
    confirm_select_ui.java_lineEdit.setObjectName("java_lineEdit")
    confirm_select_ui.verticalLayout_3.addWidget(confirm_select_ui.splitter_java)
    confirm_select_ui.java_desc = QtWidgets.QLabel(confirm_select_ui.mybatis_tab)
    confirm_select_ui.java_desc.setObjectName("java_desc")
    confirm_select_ui.verticalLayout_3.addWidget(confirm_select_ui.java_desc)
    confirm_select_ui.splitter_java_src = QtWidgets.QSplitter(confirm_select_ui.mybatis_tab)
    confirm_select_ui.splitter_java_src.setOrientation(QtCore.Qt.Horizontal)
    confirm_select_ui.splitter_java_src.setObjectName("splitter_java_src")
    confirm_select_ui.java_src = QtWidgets.QLabel(confirm_select_ui.splitter_java_src)
    confirm_select_ui.java_src.setObjectName("java_src")
    confirm_select_ui.java_src_lineEdit = QtWidgets.QLineEdit(confirm_select_ui.splitter_java_src)
    confirm_select_ui.java_src_lineEdit.setObjectName("java_src_lineEdit")
    confirm_select_ui.verticalLayout_3.addWidget(confirm_select_ui.splitter_java_src)
    confirm_select_ui.java_src_desc = QtWidgets.QLabel(confirm_select_ui.mybatis_tab)
    confirm_select_ui.java_src_desc.setObjectName("java_src_desc")
    confirm_select_ui.verticalLayout_3.addWidget(confirm_select_ui.java_src_desc)
    confirm_select_ui.splitter_model = QtWidgets.QSplitter(confirm_select_ui.mybatis_tab)
    confirm_select_ui.splitter_model.setOrientation(QtCore.Qt.Horizontal)
    confirm_select_ui.splitter_model.setObjectName("splitter_model")
    confirm_select_ui.model = QtWidgets.QLabel(confirm_select_ui.splitter_model)
    confirm_select_ui.model.setObjectName("model")
    confirm_select_ui.model_lineEdit = QtWidgets.QLineEdit(confirm_select_ui.splitter_model)
    confirm_select_ui.model_lineEdit.setObjectName("model_lineEdit")
    confirm_select_ui.verticalLayout_3.addWidget(confirm_select_ui.splitter_model)
    confirm_select_ui.model_desc = QtWidgets.QLabel(confirm_select_ui.mybatis_tab)
    confirm_select_ui.model_desc.setObjectName("model_desc")
    confirm_select_ui.verticalLayout_3.addWidget(confirm_select_ui.model_desc)
    confirm_select_ui.splitter_mapper = QtWidgets.QSplitter(confirm_select_ui.mybatis_tab)
    confirm_select_ui.splitter_mapper.setOrientation(QtCore.Qt.Horizontal)
    confirm_select_ui.splitter_mapper.setObjectName("splitter_mapper")
    confirm_select_ui.mapper = QtWidgets.QLabel(confirm_select_ui.splitter_mapper)
    confirm_select_ui.mapper.setObjectName("mapper")
    confirm_select_ui.mapper_lineEdit = QtWidgets.QLineEdit(confirm_select_ui.splitter_mapper)
    confirm_select_ui.mapper_lineEdit.setObjectName("mapper_lineEdit")
    confirm_select_ui.verticalLayout_3.addWidget(confirm_select_ui.splitter_mapper)
    confirm_select_ui.mapper_desc = QtWidgets.QLabel(confirm_select_ui.mybatis_tab)
    confirm_select_ui.mapper_desc.setObjectName("mapper_desc")
    confirm_select_ui.verticalLayout_3.addWidget(confirm_select_ui.mapper_desc)
    confirm_select_ui.splitter_xml = QtWidgets.QSplitter(confirm_select_ui.mybatis_tab)
    confirm_select_ui.splitter_xml.setOrientation(QtCore.Qt.Horizontal)
    confirm_select_ui.splitter_xml.setObjectName("splitter_xml")
    confirm_select_ui.xml = QtWidgets.QLabel(confirm_select_ui.splitter_xml)
    confirm_select_ui.xml.setObjectName("xml")
    confirm_select_ui.xml_lineEdit = QtWidgets.QLineEdit(confirm_select_ui.splitter_xml)
    confirm_select_ui.xml_lineEdit.setObjectName("xml_lineEdit")
    confirm_select_ui.verticalLayout_3.addWidget(confirm_select_ui.splitter_xml)
    confirm_select_ui.xml_desc = QtWidgets.QLabel(confirm_select_ui.mybatis_tab)
    confirm_select_ui.xml_desc.setObjectName("xml_desc")
    confirm_select_ui.verticalLayout_3.addWidget(confirm_select_ui.xml_desc)
    confirm_select_ui.tabWidget.addTab(confirm_select_ui.mybatis_tab, "")
    confirm_select_ui.spring_tab = QtWidgets.QWidget()
    confirm_select_ui.spring_tab.setObjectName("spring_tab")
    confirm_select_ui.verticalLayout_4 = QtWidgets.QVBoxLayout(confirm_select_ui.spring_tab)
    confirm_select_ui.verticalLayout_4.setObjectName("verticalLayout_4")


def setup_spring_tab_ui(confirm_select_ui):
    """
    构建spring生成器配置标签页
    :param confirm_select_ui: 弹窗确认生成器配置页的主窗口对象
    :return:
    """
    confirm_select_ui.spring_title = QtWidgets.QLabel(confirm_select_ui.spring_tab)
    confirm_select_ui.spring_title.setObjectName("spring_title")
    confirm_select_ui.verticalLayout_4.addWidget(confirm_select_ui.spring_title)
    confirm_select_ui.spring_first_blank = QtWidgets.QLabel(confirm_select_ui.spring_tab)
    confirm_select_ui.spring_first_blank.setText("")
    confirm_select_ui.spring_first_blank.setObjectName("spring_first_blank")
    confirm_select_ui.verticalLayout_4.addWidget(confirm_select_ui.spring_first_blank)
    confirm_select_ui.spring_desc = QtWidgets.QLabel(confirm_select_ui.spring_tab)
    confirm_select_ui.spring_desc.setObjectName("spring_desc")
    confirm_select_ui.verticalLayout_4.addWidget(confirm_select_ui.spring_desc)
    confirm_select_ui.spring_second_blank = QtWidgets.QLabel(confirm_select_ui.spring_tab)
    confirm_select_ui.spring_second_blank.setText("")
    confirm_select_ui.spring_second_blank.setObjectName("spring_second_blank")
    confirm_select_ui.verticalLayout_4.addWidget(confirm_select_ui.spring_second_blank)
    confirm_select_ui.spring_third_blank = QtWidgets.QLabel(confirm_select_ui.spring_tab)
    confirm_select_ui.spring_third_blank.setText("")
    confirm_select_ui.spring_third_blank.setObjectName("spring_third_blank")
    confirm_select_ui.verticalLayout_4.addWidget(confirm_select_ui.spring_third_blank)
    confirm_select_ui.spring_fourth_blank = QtWidgets.QLabel(confirm_select_ui.spring_tab)
    confirm_select_ui.spring_fourth_blank.setText("")
    confirm_select_ui.spring_fourth_blank.setObjectName("spring_fourth_blank")
    confirm_select_ui.verticalLayout_4.addWidget(confirm_select_ui.spring_fourth_blank)
    confirm_select_ui.spring_fifth_blank = QtWidgets.QLabel(confirm_select_ui.spring_tab)
    confirm_select_ui.spring_fifth_blank.setText("")
    confirm_select_ui.spring_fifth_blank.setObjectName("spring_fifth_blank")
    confirm_select_ui.verticalLayout_4.addWidget(confirm_select_ui.spring_fifth_blank)
    confirm_select_ui.splitter_service = QtWidgets.QSplitter(confirm_select_ui.spring_tab)
    confirm_select_ui.splitter_service.setOrientation(QtCore.Qt.Horizontal)
    confirm_select_ui.splitter_service.setObjectName("splitter_service")
    confirm_select_ui.service = QtWidgets.QLabel(confirm_select_ui.splitter_service)
    confirm_select_ui.service.setObjectName("service")
    confirm_select_ui.service_lineEdit = QtWidgets.QLineEdit(confirm_select_ui.splitter_service)
    confirm_select_ui.service_lineEdit.setObjectName("service_lineEdit")
    confirm_select_ui.verticalLayout_4.addWidget(confirm_select_ui.splitter_service)
    confirm_select_ui.service_desc = QtWidgets.QLabel(confirm_select_ui.spring_tab)
    confirm_select_ui.service_desc.setObjectName("service_desc")
    confirm_select_ui.verticalLayout_4.addWidget(confirm_select_ui.service_desc)
    confirm_select_ui.splitter_service_impl = QtWidgets.QSplitter(confirm_select_ui.spring_tab)
    confirm_select_ui.splitter_service_impl.setOrientation(QtCore.Qt.Horizontal)
    confirm_select_ui.splitter_service_impl.setObjectName("splitter_service_impl")
    confirm_select_ui.service_impl = QtWidgets.QLabel(confirm_select_ui.splitter_service_impl)
    confirm_select_ui.service_impl.setObjectName("service_impl")
    confirm_select_ui.service_impl_lineEdit = QtWidgets.QLineEdit(confirm_select_ui.splitter_service_impl)
    confirm_select_ui.service_impl_lineEdit.setObjectName("service_impl_lineEdit")
    confirm_select_ui.verticalLayout_4.addWidget(confirm_select_ui.splitter_service_impl)
    confirm_select_ui.service_impl_desc = QtWidgets.QLabel(confirm_select_ui.spring_tab)
    confirm_select_ui.service_impl_desc.setObjectName("service_impl_desc")
    confirm_select_ui.verticalLayout_4.addWidget(confirm_select_ui.service_impl_desc)
    confirm_select_ui.splitter_controller = QtWidgets.QSplitter(confirm_select_ui.spring_tab)
    confirm_select_ui.splitter_controller.setOrientation(QtCore.Qt.Horizontal)
    confirm_select_ui.splitter_controller.setObjectName("splitter_controller")
    confirm_select_ui.controller = QtWidgets.QLabel(confirm_select_ui.splitter_controller)
    confirm_select_ui.controller.setObjectName("controller")
    confirm_select_ui.controller_lineEdit = QtWidgets.QLineEdit(confirm_select_ui.splitter_controller)
    confirm_select_ui.controller_lineEdit.setObjectName("controller_lineEdit")
    confirm_select_ui.verticalLayout_4.addWidget(confirm_select_ui.splitter_controller)
    confirm_select_ui.controller_desc = QtWidgets.QLabel(confirm_select_ui.spring_tab)
    confirm_select_ui.controller_desc.setObjectName("controller_desc")
    confirm_select_ui.verticalLayout_4.addWidget(confirm_select_ui.controller_desc)
    confirm_select_ui.spring_sixth_blank = QtWidgets.QLabel(confirm_select_ui.spring_tab)
    confirm_select_ui.spring_sixth_blank.setText("")
    confirm_select_ui.spring_sixth_blank.setObjectName("spring_sixth_blank")
    confirm_select_ui.verticalLayout_4.addWidget(confirm_select_ui.spring_sixth_blank)
    confirm_select_ui.spring_seventh_blank = QtWidgets.QLabel(confirm_select_ui.spring_tab)
    confirm_select_ui.spring_seventh_blank.setText("")
    confirm_select_ui.spring_seventh_blank.setObjectName("spring_seventh_blank")
    confirm_select_ui.verticalLayout_4.addWidget(confirm_select_ui.spring_seventh_blank)
    confirm_select_ui.spring_eighth_blank = QtWidgets.QLabel(confirm_select_ui.spring_tab)
    confirm_select_ui.spring_eighth_blank.setText("")
    confirm_select_ui.spring_eighth_blank.setObjectName("spring_eighth_blank")
    confirm_select_ui.verticalLayout_4.addWidget(confirm_select_ui.spring_eighth_blank)


def fill_text(confirm_select_ui):
    """
    对界面上的文字样式控制
    :param confirm_select_ui: 弹窗确认生成器配置页的主窗口对象
    :return:
    """
    confirm_select_ui.mybatis_title.setText(
        confirm_select_ui._translate("Dialog", "<html><head/><body><p align=\"center\">mybatis 生成器输出配置</p></body></html>"))
    confirm_select_ui.mybatis_desc.setText(confirm_select_ui._translate("Dialog", "mybatis解释"))
    confirm_select_ui.lombok.setText(confirm_select_ui._translate("Dialog", "是否启用lombok注解"))
    confirm_select_ui.lombok_comboBox.setItemText(0, confirm_select_ui._translate("Dialog", "True"))
    confirm_select_ui.lombok_comboBox.setItemText(1, confirm_select_ui._translate("Dialog", "False"))
    confirm_select_ui.lombok_desc.setText(confirm_select_ui._translate("Dialog", "lombok解释"))
    confirm_select_ui.java.setText(confirm_select_ui._translate("Dialog", "java项目地址"))
    confirm_select_ui.java_desc.setText(confirm_select_ui._translate("Dialog", "java项目解释"))
    confirm_select_ui.java_src.setText(confirm_select_ui._translate("Dialog", "java_src"))
    confirm_select_ui.java_src_desc.setText(confirm_select_ui._translate("Dialog", "java_src解释"))
    confirm_select_ui.model.setText(confirm_select_ui._translate("Dialog", "model"))
    confirm_select_ui.model_desc.setText(confirm_select_ui._translate("Dialog", "model解释"))
    confirm_select_ui.mapper.setText(confirm_select_ui._translate("Dialog", "mapper"))
    confirm_select_ui.mapper_desc.setText(confirm_select_ui._translate("Dialog", "mapper解释"))
    confirm_select_ui.xml.setText(confirm_select_ui._translate("Dialog", "xml"))
    confirm_select_ui.xml_desc.setText(confirm_select_ui._translate("Dialog", "xml解释"))
    confirm_select_ui.tabWidget.setTabText(confirm_select_ui.tabWidget.indexOf(confirm_select_ui.mybatis_tab),
                                      confirm_select_ui._translate("Dialog", "mybatis生成器"))
    confirm_select_ui.spring_title.setText(
        confirm_select_ui._translate("Dialog", "<html><head/><body><p align=\"center\">spring 生成器配置</p></body></html>"))
    confirm_select_ui.spring_desc.setText(confirm_select_ui._translate("Dialog", "spring解释"))
    confirm_select_ui.service.setText(confirm_select_ui._translate("Dialog", "service"))
    confirm_select_ui.service_desc.setText(confirm_select_ui._translate("Dialog", "service解释"))
    confirm_select_ui.service_impl.setText(confirm_select_ui._translate("Dialog", "service_impl"))
    confirm_select_ui.service_impl_desc.setText(confirm_select_ui._translate("Dialog", "service_impl 解释"))
    confirm_select_ui.controller.setText(confirm_select_ui._translate("Dialog", "controller"))
    confirm_select_ui.controller_desc.setText(confirm_select_ui._translate("Dialog", "controller解释"))
    confirm_select_ui.tabWidget.setTabText(confirm_select_ui.tabWidget.indexOf(confirm_select_ui.spring_tab),
                                      confirm_select_ui._translate("Dialog", "spring生成器"))
    confirm_select_ui.buttonBox.button(QtWidgets.QDialogButtonBox.Ok).setText('清空本页配置')
    confirm_select_ui.buttonBox.button(QtWidgets.QDialogButtonBox.Cancel).setText('上一步')
    confirm_select_ui.buttonBox_2.button(QtWidgets.QDialogButtonBox.Ok).setText('开始生成')
    confirm_select_ui.buttonBox_2.button(QtWidgets.QDialogButtonBox.Cancel).setText('取消')
