# -*- coding: utf-8 -*-

_author_ = 'luwt'
_date_ = '2023/2/24 16:39'


SQL_CONFIRM_SELECTED_TITLE = 'sql数据源已选数据展示'
STRUCT_CONFIRM_SELECTED_TITLE = '结构体数据源已选数据展示'
RESELECT_BTN_TXT = '返回修改'
CHOOSE_TYPE_MAPPING_BTN_TXT = '选择类型映射'

SELECT_TYPE_MAPPING_TITLE = '请选择类型映射'
BACK_TO_SELECTED_DATA_BTN_TXT = '返回查看选中数据'
CHOOSE_TEMPLATE_BTN_TXT = '选择模板'

SELECT_TEMPLATE_TITLE = '请选择模板'
BACK_TO_SELECT_TYPE_MAPPING_BTN_TXT = '返回选择类型映射'
FILL_TEMPLATE_OUTPUT_CONFIG_BTN_TXT = '填写模板输出配置'

FILL_TEMPLATE_OUTPUT_CONFIG_TITLE = '请填写模板输出配置'
BACK_TO_SELECT_TEMPLATE_BTN_TXT = '返回选择模板'
FILL_TEMPLATE_VAR_CONFIG_BTN_TXT = '填写模板变量配置'

FILL_TEMPLATE_VAR_CONFIG_TITLE = '请填写模板变量配置'
BACK_TO_FILL_OUTPUT_CONFIG_BTN_TXT = '返回填写模板输出配置'
GENERATE_BTN_TXT = '生成'

GENERATE_TITLE = '生成'
BACK_TO_FILL_TEMPLATE_VAR_CONFIG_BTN_TXT = '返回填写模板变量配置'
GENERATE_TO_FILE_BTN_TXT = '生成到文件'
PREVIEW_GENERATE_BTN_TXT = '预览生成'
PREPARE_PROGRESS_LABEL_TXT = '准备工作：'
GENERATE_PROGRESS_LABEL_TXT = '生成进度：'
GENERATE_LOG_LABEL_TXT = '生成日志：'

GENERATE_TO_FILE_TITLE = '生成到文件'
PREVIEW_GENERATE_TITLE = '预览生成'
NO_FILE_TO_PREVIEW_PROMPT = '没有需要预览的文件'

PREVIEW_GENERATE_FILE_TITLE = '预览生成文件'
SAVE_FILE_BTN_TEXT = '保存到文件'
PREVIEW_TREE_LOCATE_BTN_TEXT = '定位'
PREVIEW_RENAME_FILE_NAME_BTN_TEXT = '修改文件名'
PREVIEW_TREE_FOLDER_ICON = '预览生成树结构文件夹icon'
PREVIEW_TREE_FILE_ICON = '预览生成树结构文件icon'
NO_SELECTED_FILE_ITEM_PROMPT = '请先选中目录树中的文件再进行操作'
PREVIEW_RENAME_FILE_NAME_TITLE = '修改文件名'
SAVE_PREVIEW_FILE_TITLE = '保存预览内容到文件'
SAVE_PREVIEW_FILE_PROGRESS_TEXT = '保存进度：'
