# -*- coding: utf-8 -*-

_author_ = 'luwt'
_date_ = '2023/2/24 16:39'


RESELECT_TXT = '返回修改'
CHOOSE_TYPE_MAPPING_TXT = '选择类型映射'
SQL_CONFIRM_SELECTED_HEADER_TXT = 'sql数据源已选数据展示'
STRUCT_CONFIRM_SELECTED_HEADER_TXT = '结构体数据源已选数据展示'

BACK_TO_SELECTED_DATA_TXT = '返回查看选中数据'
CHOOSE_TEMPLATE_TXT = '选择模板'
SELECT_TYPE_MAPPING_HEADER_TXT = '请选择类型映射'

BACK_TO_SELECT_TYPE_MAPPING_TXT = '返回选择类型映射'
FILL_TEMPLATE_CONFIG_TXT = '填写模板配置'
SELECT_TEMPLATE_HEADER_TXT = '请选择模板'

BACK_TO_SELECT_TEMPLATE_TXT = '返回选择模板'
PREVIEW_GENERATE_TXT = '预览生成'
GENERATE_TXT = '生成'
FILL_TEMPLATE_CONFIG_HEADER_TXT = '请填写模板配置'
