# -*- coding: utf-8 -*-

from view.tree.tree_item.abstract_tree_node import AbstractTreeNode

_author_ = 'luwt'
_date_ = '2022/12/2 11:32'


class AbstractStructTreeNode(AbstractTreeNode):

    def open_item(self): ...

    def open_item_ui(self, *args): ...

    def open_item_fail(self): ...

    def reopen_item(self, opened_items): ...

    def close_item(self): ...

    def change_check_box(self, check_state): ...

    def do_fill_menu(self, menu): ...

    def handle_menu_func(self, func): ...

    def worker_terminate(self): ...
