# -*- coding: utf-8 -*-

_author_ = 'luwt'
_date_ = '2023/6/13 18:10'


HELP_TITLE = '帮助信息'

CENTRAL_HELP = '主界面'
SQL_DS_HELP = 'sql数据源'
FOLDER_HELP = '结构体文件夹'
STRUCT_DS_HELP = '结构体数据源'
TYPE_MAPPING_TABLE_HELP = '类型映射管理'
TYPE_MAPPING_DETAIL_HELP = '类型映射详情'
DS_COL_TYPE_HELP = '数据源列类型'
TEMPLATE_TABLE_HELP = '模板管理'
TEMPLATE_DETAIL_HELP = '模板详情'
TEMPLATE_CONFIG_HELP = '模板配置详情'
TEMPLATE_MAINTAIN_FILE_CONFIG_HELP = '模板文件输出配置'
TEMPLATE_FUNC_TABLE_HELP = '模板方法管理'
TEMPLATE_FUNC_DETAIL_HELP = '模板方法详情'
IMPORT_DATA_HELP = '导入数据'
IMPORT_ERROR_DATA_HELP = '导入数据异常处理'
EXPORT_DATA_HELP = '导出数据'

HELP_TYPE_TUPLE = (CENTRAL_HELP, SQL_DS_HELP, FOLDER_HELP, STRUCT_DS_HELP,
                   TYPE_MAPPING_TABLE_HELP, TYPE_MAPPING_DETAIL_HELP, DS_COL_TYPE_HELP,
                   TEMPLATE_TABLE_HELP, TEMPLATE_DETAIL_HELP, TEMPLATE_CONFIG_HELP,
                   TEMPLATE_MAINTAIN_FILE_CONFIG_HELP, TEMPLATE_FUNC_TABLE_HELP,
                   TEMPLATE_FUNC_DETAIL_HELP, IMPORT_DATA_HELP, IMPORT_ERROR_DATA_HELP, EXPORT_DATA_HELP)
